class HomePage():
    # Single company user home page
    dateId_id = "sg.com"
    monthId_id = "sg.com"
    homePageLayout_id = "sg.com"
    # first detect if there is any unhandled issue
    # todoMark = "sg.com.trustedsource.boardVision:id/dot_resolutions_red"
    # todoMark2 = "sg.com.trustedsource.boardVision:id/dot_resolutions_green"
    noDataMark_id = "sg.com"

    # search bar contents
    searchBarBtn_id = "sg.com"
    searchBtn_id = "sg.com"
    searchTextBox_id = "sg.com"
    searchCloseBtn_id = "sg.com"
    # filter contents
    filterBtn_id = "sg.com"
    filterpopup_id = "sg.com"
    resolutionSwitch_id = "sg.com"
    scheduleSwitch_id = "sg.com"
    meetingSwitch_id = "sg.com"
    showResultsBtn_id = "sg.com"
    filterCloseBtn_id = "sg.com"

    singleEventMark_id = "sg.com"
    singleEventText_id = "sg.com"

    topEvent_xp = "Layout"
    topEventText_xp = "TextView"
    topEventText2_xp = "TextView"

    # resolution page elements
    outline_acid = "Outline"
    search_acid = "Search"
    settings_acid = "Settings"
    share_acid = "Share"
    grid_acid = "Grid"
    outline_id = "sg.com"
    annotation_id = "sg.com"
    docInfo_id = "sg.com"
    resolutionMark_id = "sg.com"
    searchBox_id = "sg.com"
    searchBack_id = "sg.com"
    settingPopup_xp = "LinearLayout"
    shareMenu_id = "sg.com"
    shareOption_id = "sg.com"
    gridSideBar_id = "sg.com"

    supDocBtn_id = "sg.com"
    topMultiSupDoc_xpath = "View"

    actionMenu_id = "sg.com"
    closeActionMenuBtn_id = "sg.com"
    approveBtn_id = "sg.com"
    disapproveBtn_id = "sg.com"
    addRemarksBtn_id = "sg.com"
    editRemarksBtn_id = "sg.com"
    remarksBox_id = "sg.com"
    updateRemarksBtn_id = "sg.com"
    continueWithRemarks_id = "sg.com"
    accessFilePop_id = "com.android."
    allowAccessBtn_id = "com.android"
    loadSignatureBtn_id = "sg.com"
    emptySignPad_id = "sg.com"
    clearSignatureBtn_id = "sg.com"
    continueToAction_id = "sg.com"
    actionMark_id = "sg.com"
    otpMark_id = "sg.com"
    resoBackBtn_id = "sg.com"

    # schedule page elements
    schedulePageTitle_id = "sg.com"
    scheBackBtn_id = "sg.com"
    scheVote_id = "sg.com"
    scheUpdateBtn_id = "sg.com
    scheExitPopup_id = "sg.com"
    scheNoExitBtn_id = "sg.com"
    scheExitBtn_id = "sg.com"

    # meeting page elements
    agendaBtn_id = "sg.com"
    otherDocBtn_id = "sg.com"
    participantBtn_id = "sg.com"
    agendaMark_id = "sg.com"
    otherDocMark_id = "sg.com"
    participantMark_id = "sg.com"
    meetingBackBtn_id = "sg.com"
    noMeetingDataMark_id = "sg.com"
    singleDocMark_id = "sg.com"
    topMultiDoc_xpath = "RelativeLayout"
    pdfPage_id = "sg.com"
    sharePopupTitle_id = "sg.com"
    singleAgendaMark_id = "sg.com"
    topMultiAgenda_xpath = "RelativeLayout"
    
