class HomePage():
    # Single company user home page
    dateId_id = "sg.com.trustedsource.boardVision:id/toolbar_date"
    monthId_id = "sg.com.trustedsource.boardVision:id/toolbar_month"
    homePageLayout_id = "sg.com.trustedsource.boardVision:id/scroll"
    # first detect if there is any unhandled issue
    # todoMark = "sg.com.trustedsource.boardVision:id/dot_resolutions_red"
    # todoMark2 = "sg.com.trustedsource.boardVision:id/dot_resolutions_green"
    noDataMark_id = "sg.com.trustedsource.boardVision:id/noData"

    # search bar contents
    searchBarBtn_id = "sg.com.trustedsource.boardVision:id/new_search_v2"
    searchBtn_id = "sg.com.trustedsource.boardVision:id/searchIcon"
    searchTextBox_id = "sg.com.trustedsource.boardVision:id/search_text"
    searchCloseBtn_id = "sg.com.trustedsource.boardVision:id/closeicon"
    # filter contents
    filterBtn_id = "sg.com.trustedsource.boardVision:id/all_categories_v2"
    filterpopup_id = "sg.com.trustedsource.boardVision:id/titlelayout_v2"
    resolutionSwitch_id = "sg.com.trustedsource.boardVision:id/resolution_switch"
    scheduleSwitch_id = "sg.com.trustedsource.boardVision:id/scheduling_switch"
    meetingSwitch_id = "sg.com.trustedsource.boardVision:id/meeting_switch"
    showResultsBtn_id = "sg.com.trustedsource.boardVision:id/decline"
    filterCloseBtn_id = "sg.com.trustedsource.boardVision:id/close_v2"

    singleEventMark_id = "sg.com.trustedsource.boardVision:id/layout_1"
    singleEventText_id = "sg.com.trustedsource.boardVision:id/title_of_content"

    topEvent_xp = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/androidx.viewpager.widget.ViewPager/android.widget.RelativeLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout"
    topEventText_xp = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/androidx.viewpager.widget.ViewPager/android.widget.RelativeLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.TextView"
    topEventText2_xp = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/androidx.viewpager.widget.ViewPager/android.widget.RelativeLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.RelativeLayout/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.TextView"

    # resolution page elements
    outline_acid = "Outline"
    search_acid = "Search"
    settings_acid = "Settings"
    share_acid = "Share"
    grid_acid = "Grid"
    outline_id = "sg.com.trustedsource.boardVision:id/pspdf__menu_pdf_outline_view_outline"
    annotation_id = "sg.com.trustedsource.boardVision:id/pspdf__menu_pdf_outline_view_annotations"
    docInfo_id = "sg.com.trustedsource.boardVision:id/pspdf__menu_pdf_outline_view_document_info"
    resolutionMark_id = "sg.com.trustedsource.boardVision:id/pspdf__document_view"
    searchBox_id = "sg.com.trustedsource.boardVision:id/pspdf__search_inline_layout"
    searchBack_id = "sg.com.trustedsource.boardVision:id/pspdf__search_btn_back"
    settingPopup_xp = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout"
    shareMenu_id = "sg.com.trustedsource.boardVision:id/pspdf__fixed_menu_recycler_view"
    shareOption_id = "sg.com.trustedsource.boardVision:id/pspdf__standard_menu_recycler_view"
    gridSideBar_id = "sg.com.trustedsource.boardVision:id/thumbnailGridDrawer"

    supDocBtn_id = "sg.com.trustedsource.boardVision:id/supportdoc_icon"
    topMultiSupDoc_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.ScrollView/android.widget.RelativeLayout/android.widget.RelativeLayout[2]/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.view.View"

    actionMenu_id = "sg.com.trustedsource.boardVision:id/xmenu_v2"
    closeActionMenuBtn_id = "sg.com.trustedsource.boardVision:id/xclose"
    approveBtn_id = "sg.com.trustedsource.boardVision:id/approveLayout"
    disapproveBtn_id = "sg.com.trustedsource.boardVision:id/disapproveLayout"
    addRemarksBtn_id = "sg.com.trustedsource.boardVision:id/addRemarks"
    editRemarksBtn_id = "sg.com.trustedsource.boardVision:id/addremarks_title"
    remarksBox_id = "sg.com.trustedsource.boardVision:id/leavecomment"
    updateRemarksBtn_id = "sg.com.trustedsource.boardVision:id/Continue"
    continueWithRemarks_id = "sg.com.trustedsource.boardVision:id/Continue"
    accessFilePop_id = "com.android.permissioncontroller:id/content_container"
    allowAccessBtn_id = "com.android.permissioncontroller:id/permission_allow_button"
    loadSignatureBtn_id = "sg.com.trustedsource.boardVision:id/load"
    emptySignPad_id = "sg.com.trustedsource.boardVision:id/signature_pad_description"
    clearSignatureBtn_id = "sg.com.trustedsource.boardVision:id/clear_button"
    continueToAction_id = "sg.com.trustedsource.boardVision:id/save_button"
    actionMark_id = "sg.com.trustedsource.boardVision:id/title"
    otpMark_id = "sg.com.trustedsource.boardVision:id/createpin"
    resoBackBtn_id = "sg.com.trustedsource.boardVision:id/back"

    # schedule page elements
    schedulePageTitle_id = "sg.com.trustedsource.boardVision:id/title"
    scheBackBtn_id = "sg.com.trustedsource.boardVision:id/back"
    scheVote_id = "sg.com.trustedsource.boardVision:id/layout1"
    scheUpdateBtn_id = "sg.com.trustedsource.boardVision:id/done"
    scheExitPopup_id = "sg.com.trustedsource.boardVision:id/closelayout"
    scheNoExitBtn_id = "sg.com.trustedsource.boardVision:id/decline"
    scheExitBtn_id = "sg.com.trustedsource.boardVision:id/confirm"

    # meeting page elements
    agendaBtn_id = "sg.com.trustedsource.boardVision:id/agenta_title"
    otherDocBtn_id = "sg.com.trustedsource.boardVision:id/participants_title"
    participantBtn_id = "sg.com.trustedsource.boardVision:id/otherdocuments_title"
    agendaMark_id = "sg.com.trustedsource.boardVision:id/textAgenda"
    otherDocMark_id = "sg.com.trustedsource.boardVision:id/text_parti"
    participantMark_id = "sg.com.trustedsource.boardVision:id/text_partii"
    meetingBackBtn_id = "sg.com.trustedsource.boardVision:id/back"
    noMeetingDataMark_id = "sg.com.trustedsource.boardVision:id/nodata_found"
    singleDocMark_id = "sg.com.trustedsource.boardVision:id/open_close"
    topMultiDoc_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.view.ViewGroup[2]/android.widget.ScrollView/android.widget.RelativeLayout/androidx.viewpager.widget.ViewPager/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.RelativeLayout"
    pdfPage_id = "sg.com.trustedsource.boardVision:id/pspdf__document_view"
    sharePopupTitle_id = "sg.com.trustedsource.boardVision:id/pspdf_share_dialog_title"
    singleAgendaMark_id = "sg.com.trustedsource.boardVision:id/cardView"
    topMultiAgenda_xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.view.ViewGroup[2]/android.widget.ScrollView/android.widget.RelativeLayout/androidx.viewpager.widget.ViewPager/android.widget.RelativeLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]"
    
